server:
  port: 8080
spring:
  flyway:
    locations: classpath:db/migrations
    sqlMigrationPrefix: PM-
  datasource:
    url: jdbc:mysql://sql3.freemysqlhosting.net:3306/sql3730302?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    password: sNFaSGhDgR
    username: sql3730302
  jpa:
    properties:
      hibernate:
        jdbc:
          metadata:
            access:
              allow: true
security:
  jwt:
    token:
      secret-key: mySecretKey
cors:
  allowed-origins:
    - http://localhost:3000

